### ISSUE TITLE
Use outside of a compose app

### ISSUE THREAD

**Issue by androidacy-user** [mikepenz/multiplatform-markdown-renderer#116]
## About this issue

Hi! We have no interest in using Compose, whereas your library seems to mandate the use of Compose.

Also, unfortunately for us, your library seems to be one of the only libraries for rendering markdown that's decently maintained.

Perhaps we are missing how to use it without compose (Markdown(text) does not work, outside of a composable function), or is there plans to support non compose Android apps?

## Details
- [x] Used library version 0.12.0
- [ ] Used platform
- [ ] Used support library version
- [x] Used gradle build tools version 8.2.2
- [x] Used tooling / Android Studio version Android Gradle Plugin 8.2.2
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/multiplatform-markdown-renderer/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/multiplatform-markdown-renderer/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/multiplatform-markdown-renderer/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
Good day @androidacy-user and thank you for raising this question. 

There are no plans to have a view-only variant of this library as its main target was compose (and even compose multiplatform apps). 

For using it in a view-based app I can only refer to this resource: https://developer.android.com/jetpack/compose/migrate/interoperability-apis/compose-in-views

You will also need to provide a material2 or material3 compose theme to make it look as you want. 

I hope that helps.
