### ISSUE TITLE
Images are invisible

### ISSUE THREAD

**Issue by androidacy-user** [mikepenz/multiplatform-markdown-renderer#121]
## About this issue

Hello! When trying to render markdown, images do not show. However, if they are linked, clicking on the empty space where they should be opens the link

## Details
- [x] Used library version 0.13.0
- [x] Used platform Android, via ComposeView
- [ ] Used support library version
- [x] Used gradle build tools version 8.3.1
- [x] Used tooling / Android Studio version Iguana 2023.2.1
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/multiplatform-markdown-renderer/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/multiplatform-markdown-renderer/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/multiplatform-markdown-renderer/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
Can you please provide some additional details, like sample code to reproduce this, can you reproduce this in the sample app? (Which has images loading as well)?

**Comment by mikepenz** [comment]
Updated the README based on your PR. thank you very much

**Comment by mikepenz** [comment]
Can you please elaborate? Which type of tags do you mean?

**Comment by mikepenz** [comment]
<img width="1145" alt="Screenshot 2024-06-21 at 10 37 17" src="https://github.com/mikepenz/multiplatform-markdown-renderer/assets/1476232/2c4695c4-e4a6-4304-bbb0-16e146ef8c34">

Markdown exposes html elements as `HTML_TAG`.

As noted earlier I don't plan to build a HTML parsers, however an upcoming feature in compose foundation (https://developer.android.com/jetpack/androidx/releases/compose-foundation#1.7.0-alpha07) might be interesting to parse HTML as spannable string

<img width="736" alt="Screenshot 2024-06-21 at 10 38 44" src="https://github.com/mikepenz/multiplatform-markdown-renderer/assets/1476232/cf79889f-03d3-4096-a79d-6e0ae23231f8">

It's worth noting that I am not sure if that would support images (I honestly doubt it) 
It's something which can be explored once compose 1.7 hits stable channels for compose multiplatform. 


Regardless of that. given the flexibility of the `Markdown` API you can expand your own annotated strings handling. As shown below:

```kotlin
Markdown(
    """[<img src="https://avatars.githubusercontent.com/u/1476232?v=4" class="img-fluid rounded m-1" alt="XDA-Developers" loading="lazy">](https://forum.xda-developers.com/android/software/bromite-magisk-module-t3936964)""",
    annotator = markdownAnnotator { content, child ->
        if (child.type == MarkdownTokenTypes.HTML_TAG) {
            // val htmlContent = child.getTextInNode(content).toString()
            // TODO define your HTML parsing logic
            appendInlineContent(
                "TAG_IMAGE_URL",
                "https://avatars.githubusercontent.com/u/1476232?v=4"
            )
            true
        }

        false
    },
    imageTransformer = Coil2ImageTransformerImpl,
    modifier = Modifier.fillMaxSize().verticalScroll(scrollState).padding(16.dp)
)
```

**Comment by mikepenz** [comment]
Because coil3 uses a snapshot build and the latest snapshot of coil has breaking changes. Wait a few hours before I am able to update to coil3 alpha07
