### ISSUE TITLE
CompositionLocal ReferenceLinkHandler not present

### ISSUE THREAD

**Issue by N7ghtm4r3** [mikepenz/multiplatform-markdown-renderer#122]
## About this issue

Using this composable to customize the text style appeareance, because just the **Markdown** composable does not look change as needed:

```kotlin
MarkdownText(
   modifier = Modifier
       .padding(
           start = 5.dp,
       ),
    content = "content",
    style = TextStyle(
        fontFamily = myCustomFontFamily
    )
)
```

the executions produces this trace:

```java
Exception in thread "AWT-EventQueue-0" java.lang.IllegalStateException: CompositionLocal ReferenceLinkHandler not present
	at com.mikepenz.markdown.compose.ComposeLocalKt$LocalReferenceLinkHandler$1.invoke(ComposeLocal.kt:25)
	at com.mikepenz.markdown.compose.ComposeLocalKt$LocalReferenceLinkHandler$1.invoke(ComposeLocal.kt:24)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at androidx.compose.runtime.LazyValueHolder.getCurrent(ValueHolders.kt:29)
	at androidx.compose.runtime.LazyValueHolder.getValue(ValueHolders.kt:31)
	at androidx.compose.runtime.CompositionLocalMapKt.read(CompositionLocalMap.kt:90)
	at androidx.compose.runtime.ComposerImpl.consume(Composer.kt:2136)
	at com.mikepenz.markdown.compose.elements.MarkdownTextKt.MarkdownText(MarkdownText.kt:106)
	at com.mikepenz.markdown.compose.elements.MarkdownTextKt.MarkdownText(MarkdownText.kt:33
```

## Details
- [0.13.0] Used library version
- [ Desktop] Used platform
- [-m3 ] Used support library version

**Comment by mikepenz** [comment]
If you don't use the full `Markdown` which is the main exposed API then you will need to provide the composition:

```
https://github.com/mikepenz/multiplatform-markdown-renderer/blob/c03619a4c13a0a587f436eb2b3e64021cd1e86d5/multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/Markdown.kt#L48
```

Is there any reason you don't use `Markdown` as shown in the README: https://github.com/mikepenz/multiplatform-markdown-renderer?tab=readme-ov-file#usage ?

**Comment by N7ghtm4r3** [comment]
Thanks for the reply, I will take a look to provides the composition if this Is allowed.
The reasons because I don't use the `Markdown` composable is because the text is not shown as needed, for example the custom `fontFamily` that I want to use is not loaded

**Comment by N7ghtm4r3** [comment]
There is a way to use `style` like in 

```kotlin
MarkdownText(
    modifier = Modifier
        .padding(
            start = 5.dp,
        ),
    content = release.releaseNotes.content,
    style = TextStyle( // like this
        fontFamily = thinFontFamily
    )
)
```

in the `Markdown` composable?
Because I tried to provide the local composition as you shown, but the text is like is not rendered in markdown format

**Comment by mikepenz** [comment]
You can provide the typography: 

https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/multiplatform-markdown-renderer-m3/src/commonMain/kotlin/com/mikepenz/markdown/m3/Markdown.kt#L16

**Comment by mikepenz** [comment]
Please provide a full snippet on what you tried. 

Because if I do: 

```
Markdown(
    content,
    typography = markdownTypography(h1 = MaterialTheme.typography.body1),
    modifier = Modifier.fillMaxSize().verticalScroll(scrollState).padding(16.dp)
)
```

I can definitely see that the typography of body1 is applied to `h1` titles.

**Comment by N7ghtm4r3** [comment]
I tried to use that composable with the configuration [MarkdownSnippet.zip](https://github.com/mikepenz/multiplatform-markdown-renderer/files/14726886/MarkdownSnippet.zip). 
The composable snippet:

```kotlin
Markdown(
    content = mycontent,
    typography = markdownTypography(text = Typography.displaySmall)
)
```

**Comment by N7ghtm4r3** [comment]
Yes the main request is that,  is wrong to use text?

**Comment by N7ghtm4r3** [comment]
Thank you for the help! I will try to configure both
