### ISSUE TITLE
[FEATURE REQUEST] Syntax highlighting

### ISSUE THREAD

**Issue by androidacy-user** [mikepenz/multiplatform-markdown-renderer#124]
Hey 👋🏾 

I was wondering if you would consider adding syntax highlighting for code blocks (perhaps on an opt-in basis?) to this library, using something like https://github.com/wingio/syntakts perhaps.

Thanks for your time.

**Comment by mikepenz** [comment]
Thank you for the suggestion. I think you should be able to already be able to do that, by adding a custom handling for the `Code` block. 

Might be interesting to add an example for that, but I don't think that I plan to have it as a core part of the project at this time 🤔

**Comment by mikepenz** [comment]
https://github.com/mikepenz/multiplatform-markdown-renderer?tab=readme-ov-file#syntax-highlighting
