### ISSUE TITLE
[FEATURE_REQUEST] Add maxLines attribute

### ISSUE THREAD

**Issue by ThyMYthOS** [mikepenz/multiplatform-markdown-renderer#128]
## About this issue

- Add an attribute `maxLines` to limit the amount of rendered lines
- Optional: Add an elipsis at the end if not all text is displayed

See also https://github.com/jeziellago/compose-markdown

**Comment by mikepenz** [comment]
While we ended up not exposing maxLines for the `Markdown` component itself. Instead v0.28.0 adds a new API that allows you to build an annotated string from markdown content, that you can then use with for example the default `Text` composable.

https://github.com/mikepenz/multiplatform-markdown-renderer/issues/246#issuecomment-2564730485
