### ISSUE TITLE
Bug report: dividers are never rendered

### ISSUE THREAD

**Issue by ZacSweers** [mikepenz/multiplatform-markdown-renderer#131]
## About this issue

If I render the following snippet in markdown, I never see horizontal lines rendered

```
This is a divider

---

The above is a divider
```

Will render like so

<img width="321" alt="image" src="https://github.com/mikepenz/multiplatform-markdown-renderer/assets/1361086/019ee7d4-6a4a-495d-af05-cb425ea953da">

## Details
- [x] Used library version - 0.14.0
- [x] Used platform - Desktop
- [ ] Used support library version
- [ ] Used gradle build tools version - N/A
- [ ] Used tooling / Android Studio version - N/A
- [x] Other used libraries, potential conflicting libraries - Jewel

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/multiplatform-markdown-renderer/issues)
  - This seems similar to #99, but horizontal dividers were marked as fixed in 0.11.0 after that issue
- [x] Checked out the [sample application](https://github.com/mikepenz/multiplatform-markdown-renderer/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/multiplatform-markdown-renderer/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
Thank you for the report. This might be a theming matter. 

<img width="636" alt="Screenshot 2024-04-25 at 20 23 13" src="https://github.com/mikepenz/multiplatform-markdown-renderer/assets/1476232/57b93353-bd8f-490d-b1d5-82ab390d7d00">

<img width="436" alt="Screenshot 2024-04-25 at 20 23 36" src="https://github.com/mikepenz/multiplatform-markdown-renderer/assets/1476232/d5bc6f3d-5c97-4ca2-b4bf-5f7b9035109e">


You can pass a custom color to the `dividerColor` via the `markdownColors()`

By default it uses `MaterialTheme.colors.onSurface.copy(alpha = 0.12f)`

**Comment by ZacSweers** [comment]
Hmm, I'm not sure. I tested with even using `Color.Red` hardcoded and had the same issue. You can find a repro here: https://github.com/slackhq/slack-gradle-plugin/pull/825

**Comment by ZacSweers** [comment]
Note that the linked project isn't using material, but rather an intellij-esque theme built by jetbrains for use in IJ plugins called Jewel

**Comment by ZacSweers** [comment]
Interestingly, while trying to implement [this fix](https://github.com/mikepenz/multiplatform-markdown-renderer/issues/133#issuecomment-2077989331), it suddenly started working when I specified a custom component lambda 🤔.

<img width="356" alt="image" src="https://github.com/mikepenz/multiplatform-markdown-renderer/assets/1361086/5525549a-efea-4bd2-8285-f75928d79410">

<img width="833" alt="image" src="https://github.com/mikepenz/multiplatform-markdown-renderer/assets/1361086/cd252fa7-a21a-418e-ba1f-2e8883b5e58e">

**Comment by ZacSweers** [comment]
More interestingly, even though it appears now, I don't seem to be able to change the color even if I hardcode `dividerColor` to something like `Color.Red`

**Comment by mikepenz** [comment]
I am trying to get the referenced branch compiling. However when running I'd see: 
```
Caused by: java.lang.ClassNotFoundException: androidx.collection.ScatterMapKt
```

**Comment by ZacSweers** [comment]
It looks like it's because `MarkdownDivider` doesn't use `dividerColor` 😅. That'd explain it

<img width="620" alt="image" src="https://github.com/mikepenz/multiplatform-markdown-renderer/assets/1361086/8fde997f-9966-4309-b776-8e051f2ecfdb">

**Comment by mikepenz** [comment]
🤕  Oh wow. I overlooked that also now going through it 5 times.
