### ISSUE TITLE
Feature request: Support strikethrough

### ISSUE THREAD

**Issue by ZacSweers** [mikepenz/multiplatform-markdown-renderer#133]
## About this issue

Currently, strikethrough nodes are omitted from the rendered markdown.

```
~~This is strikethrough~~
```

## Details
- [x] Used library version - 0.14.0
- [x] Used platform - Desktop
- [ ] Used support library version
- [ ] Used gradle build tools version - N/A
- [ ] Used tooling / Android Studio version - N/A
- [x] Other used libraries, potential conflicting libraries - Jewel

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/multiplatform-markdown-renderer/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/multiplatform-markdown-renderer/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/multiplatform-markdown-renderer/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
I am afraid this is currently not exposed from the markdown library. 

Example for italic text:
<img width="783" alt="Screenshot 2024-04-25 at 20 29 30" src="https://github.com/mikepenz/multiplatform-markdown-renderer/assets/1476232/e131877d-fad1-4353-a802-b5d208192601">

In comparison strikethrough text:
<img width="756" alt="Screenshot 2024-04-25 at 20 30 05" src="https://github.com/mikepenz/multiplatform-markdown-renderer/assets/1476232/45a141b8-0659-4187-80d9-95ed55048684">

It only exposes EMPH or STRONG at this time:
- https://github.com/JetBrains/markdown/blob/76cec19922613609a5b2ab8110df830c708f7214/src/commonMain/kotlin/org/intellij/markdown/MarkdownElementTypes.kt#L26-L29

**Comment by ZacSweers** [comment]
Interesting, let me file something on their side for this!

**Comment by ZacSweers** [comment]
It looks like this is supported as a GFM-specific extension here: https://github.com/JetBrains/markdown/blob/76cec19922613609a5b2ab8110df830c708f7214/src/commonMain/kotlin/org/intellij/markdown/flavours/gfm/GFMElementTypes.kt#L29

Is that something we can configure in this library?

**Comment by mikepenz** [comment]
Thanks, had overlooked this one. Need to check why it is parsed differently than the emph and strong ones. 

And yes, any type not handled can be handled via the `custom` component support: https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/Markdown.kt#L98

**Comment by mikepenz** [comment]
Good news. With the `~~text~~` it parses it properly. will include it.

**Comment by ZacSweers** [comment]
Nice!

**Comment by mikepenz** [comment]
Also a perhaps relevant note as I saw your code snippet for the `custom` component. 

`Strikethrough` is part of the annotated string: https://github.com/mikepenz/multiplatform-markdown-renderer/blob/ef34d93c2bf8dbfb0488b0db65357c339d72b6b2/multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/utils/AnnotatedStringKtx.kt
Which would require the `Paragraph` component to be overwritten and then it's internal parsing. I didn't consider this in the prior message. Given that, it would probably be quite more effort than a simple top level component. 
Already exposed most classes to make that simpler, but it would still be quite a lift. 

It might be a great addition to the library to also allow expanding the `buildMarkdownAnnotatedString` with custom conditions, so it is simpler to adjust this.
