### ISSUE TITLE
Incorrect markdown nested rendering

### ISSUE THREAD

**Issue by whitescent** [mikepenz/multiplatform-markdown-renderer#147]
Thanks a lot for having such a good markdown rendering library! 👍  It basically parses most markdown content, and is also highly customizable, but in some text, it takes the outermost syntax of the markdown with it, resulting in a nested markdown text, which it can't render properly.

Here is a reproducible text:

--------------------------------------------------------------------------------------------------

Sure, here is a sample complex markdown text with code snippets:

\```
\# Markdown Sample

This is an example of a complex markdown text that includes code snippets:

\## Code Snippet in Python

\```python
def greet(name):
    print(f"Hello, {name}!")
    
greet("Alice")
\```

\## Code Snippet in JavaScript

\```javascript
function greet(name) {
    console.log(`Hello, ${name}!`);
}

greet("Bob");
\```

You can format code in markdown using triple backticks followed by the language name.

\```
Feel free to modify and use this markdown text as needed.

-------------------------------------------------

In github, it will render as:

<img width="916" alt="image" src="https://github.com/mikepenz/multiplatform-markdown-renderer/assets/31311826/ec0fee25-dbac-448b-bb6b-c8d80e844a0b">

but the library will render as:

<img width="734" alt="image" src="https://github.com/mikepenz/multiplatform-markdown-renderer/assets/31311826/f1db0668-1511-4178-b893-5b1f50231856">

**Comment by mikepenz** [comment]
Please retry when we release the latest version. As the provided example appears to render fine:

<img width="1238" alt="Screenshot 2024-06-20 at 14 33 44" src="https://github.com/mikepenz/multiplatform-markdown-renderer/assets/1476232/be268c2a-af17-4d1f-b0bd-8e8d36803479">

**Comment by mikepenz** [comment]
Also make sure your `Markdown` is scrollable, otherwise the code block could be shrinked

**Comment by keta1** [comment]
```
无序列表使用连字符 `-`、星号 `*` 或加号 `+` 开头
```
![telegram-cloud-photo-size-5-6107018899196330385-y](https://github.com/user-attachments/assets/e2c09147-4fe7-4058-861d-a17fa91bc381)
how to solve this problem

**Comment by whitescent** [comment]
I just tested on the lastest version (0.24.0), It still doesn't seem to display correctly. Did I miss something?

<img width="1236" alt="image" src="https://github.com/user-attachments/assets/a552ff1a-aff5-4a2e-a37e-6572acea1d1b">

**Comment by mikepenz** [comment]
Can you provide a small sample for this please? Do you also use the latest version of: https://github.com/JetBrains/markdown ?

**Comment by mikepenz** [comment]
<img width="827" alt="Screenshot 2024-07-18 at 19 09 40" src="https://github.com/user-attachments/assets/a5aa94db-0164-4ab7-ae93-fef420fd0aa7">

Also make sure you put it in a scrollable container

<img width="679" alt="Screenshot 2024-07-18 at 19 10 12" src="https://github.com/user-attachments/assets/2688d211-586c-4883-a1f4-51acd58afeba">

**Comment by whitescent** [comment]
<img width="1767" alt="image" src="https://github.com/user-attachments/assets/016950df-220a-472a-aa6c-fb138a287f23">

I just create a new Compose Multiplatform and use the `render-m2` dependency, and it will still be able to reproduce.

<img width="1236" alt="image" src="https://github.com/user-attachments/assets/e1393f93-341a-425d-85d2-94166d464e43">

And their dependencies are up to date

code:

```kotlin
@Composable
@Preview
fun App() {
  Markdown(
    content = """
            Sure, here is a sample complex markdown text with code snippets:

            ```
            # Markdown Sample

            This is an example of a complex markdown text that includes code snippets:

            ## Code Snippet in Python

            ```python
            def greet(name):
            print(f"Hello, {name}!")

            greet("Alice")
            ```

            ## Code Snippet in JavaScript

            ```javascript
            function greet(name) {
            console.log(Hello, \$\{name}!);
            }

            greet("Bob");
            ```

            You can format code in markdown using triple backticks followed by the language name.

            ```
            Feel free to modify and use this markdown text as needed.
          """.trimIndent(),
    modifier = Modifier.verticalScroll(rememberScrollState())
  )
}
```

**Comment by whitescent** [comment]
<img width="1310" alt="image" src="https://github.com/user-attachments/assets/b50d06a4-34ac-40ee-b2f9-3a74fa218f71">

I just added a new line feed to the end of this line, and it renders normally 🥲

**Comment by mikepenz** [comment]
That is strange. As you can see here, I am also not adding a new line :/ 

<img width="784" alt="Screenshot 2024-07-19 at 13 42 25" src="https://github.com/user-attachments/assets/ab743dda-34ef-439a-a0f7-b752449a59e2">

I wonder what might be different between the two versions

**Comment by whitescent** [comment]
It looks like it's the `trimIndent` that's affecting it, i just tested this, If you add `trimIndent`, it has to do with whether or not there's a blank line in the last line, and if you don't have trimIndent, then it renders fine

**Comment by mikepenz** [comment]
@whitescent this was it!. Will be fixed in the next update
