### ISSUE TITLE
0.20.0 depends on a Coil snapshot

### ISSUE THREAD

**Issue by ZacSweers** [mikepenz/multiplatform-markdown-renderer#154]
## About this issue

Repro: https://github.com/slackhq/slack-gradle-plugin/pull/854

```
    > Could not find io.coil-kt.coil3:coil-compose:3.0.0-SNAPSHOT.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/io/coil-kt/coil3/coil-compose/3.0.0-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/io/coil-kt/coil3/coil-compose/3.0.0-SNAPSHOT/coil-compose-3.0.0-SNAPSHOT.pom
Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
       - https://dl.google.com/dl/android/maven2/io/coil-kt/coil3/coil-compose/3.0.0-SNAPSHOT/maven-metadata.xml
       - https://dl.google.com/dl/android/maven2/io/coil-kt/coil3/coil-compose/3.0.0-SNAPSHOT/coil-compose-3.0.0-SNAPSHOT.pom
       - https://packages.jetbrains.team/maven/p/kpm/public/io/coil-kt/coil3/coil-compose/3.0.0-SNAPSHOT/maven-metadata.xml
       - https://packages.jetbrains.team/maven/p/kpm/public/io/coil-kt/coil3/coil-compose/3.0.0-SNAPSHOT/coil-compose-3.0.0-SNAPSHOT.pom
       - https://maven.pkg.jetbrains.space/public/p/compose/dev/io/coil-kt/coil3/coil-compose/3.0.0-SNAPSHOT/maven-metadata.xml
       - https://maven.pkg.jetbrains.space/public/p/compose/dev/io/coil-kt/coil3/coil-compose/3.0.0-SNAPSHOT/coil-compose-3.0.0-SNAPSHOT.pom
       - file:/home/runner/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2023.2.1/b51a90b0b585e631c033896a64083d706ed6d71d/ideaIC-2023.2.1/io.coil-kt.coil3/coil-compose/3.0.0-SNAPSHOT/ivy-3.0.0-SNAPSHOT.xml
       - file:/home/runner/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2023.2.1/b51a90b0b585e631c033896a64083d706ed6d71d/ideaIC-2023.2.1/coil-compose-3.0.0-SNAPSHOT-2-withKotlin.xml
       - file:/home/runner/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/io.coil-kt.coil3/coil-compose-3.0.0-SNAPSHOT-3.xml
     Required by:
         project :skate-plugin > project :skate-plugin:project-gen > com.mikepenz:multiplatform-markdown-renderer:0.20.0 > com.mikepenz:multiplatform-markdown-renderer-jvm:0.20.0
```

## Details
- [x] Used library version - 0.20.0
- [x] Used platform - JVM
- [ ] Used support library version N/A
- [x] Used gradle build tools version 8.7
- [x] Used tooling / Android Studio version IntelliJ
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/multiplatform-markdown-renderer/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/multiplatform-markdown-renderer/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/multiplatform-markdown-renderer/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/MIGRATION.md)

**Comment by ZacSweers** [comment]
Snapshots cause unreproducible builds and are a no go for anything other than testing preview builds, I filed the issue because I assumed it was accidental 🤔

**Comment by ZacSweers** [comment]
Any reason not to use a pre-release non-snapshot? i.e. https://github.com/coil-kt/coil/releases/tag/3.0.0-alpha06

**Comment by mikepenz** [comment]
This was an oversight on my end. Intended to keep it as pre release until the next version of coil. 

Kotlin 2.0 was too exciting

Will make a release with the prior version in the next days.

**Comment by mikepenz** [comment]
I will release a v0.20.0-coil2 build keeping the dev on coil3 -> will do a new build once we have a new coil version. Thank you for the report

**Comment by ZacSweers** [comment]
> Will need to wait for a new alpha which supports recent compose versions.

Could you elaborate on what this support entails?

**Comment by ZacSweers** [comment]
The compose compiler is a compile-time only dependency though, depending on libraries built against it doesn't matter.

**Comment by ZacSweers** [comment]
Yes, it is. The compose-compiler is a compiler plugin and it is only used at build time. It is _not_ shipped as a compile dependency on any compose libraries that are built using it. To use this library as an example: look at its [pom](https://repo1.maven.org/maven2/com/mikepenz/multiplatform-markdown-renderer-android/0.20.0-coil2/multiplatform-markdown-renderer-android-0.20.0-coil2.pom).

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <!-- This module was also published with a richer model, Gradle metadata,  -->
  <!-- which should be used instead. Do not delete the following line which  -->
  <!-- is to indicate to Gradle or any Gradle module metadata file consumer  -->
  <!-- that they should prefer consuming it instead. -->
  <!-- do_not_remove: published-with-gradle-metadata -->
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.mikepenz</groupId>
  <artifactId>multiplatform-markdown-renderer-android</artifactId>
  <version>0.20.0-coil2</version>
  <packaging>aar</packaging>
  <name>Multiplatform Markdown Renderer</name>
  <description>Kotlin Multiplatform Markdown Renderer. (Android, Desktop, ...) powered by Compose Multiplatform</description>
  <url>https://github.com/mikepenz/multiplatform-markdown-renderer</url>
  <licenses>
    <license>
      <name>Apache-2.0</name>
      <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
      <distribution>repo</distribution>
    </license>
  </licenses>
  <developers>
    <developer>
      <id>mikepenz</id>
      <name>Mike Penz</name>
      <email>mikepenz@gmail.com</email>
    </developer>
  </developers>
  <scm>
    <connection>scm:git@github.com:mikepenz/multiplatform-markdown-renderer.git</connection>
    <developerConnection>scm:git@github.com:mikepenz/multiplatform-markdown-renderer.git</developerConnection>
    <url>https://github.com/mikepenz/multiplatform-markdown-renderer</url>
  </scm>
  <dependencies>
    <dependency>
      <groupId>org.jetbrains</groupId>
      <artifactId>markdown-jvm</artifactId>
      <version>0.7.2</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.jetbrains.kotlin</groupId>
      <artifactId>kotlin-stdlib</artifactId>
      <version>2.0.0</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>io.coil-kt</groupId>
      <artifactId>coil-compose</artifactId>
      <version>2.6.0</version>
      <scope>runtime</scope>
      <exclusions>
        <exclusion>
          <groupId>org.jetbrains.kotlin</groupId>
          <artifactId>kotlin-stdlib-common</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.jetbrains.kotlin</groupId>
          <artifactId>kotlin-test-common</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.jetbrains.kotlin</groupId>
          <artifactId>kotlin-test-annotations-common</artifactId>
        </exclusion>
        <exclusion>
          <groupId>androidx.compose.foundation</groupId>
          <artifactId>*</artifactId>
        </exclusion>
        <exclusion>
          <groupId>androidx.compose.ui</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
  </dependencies>
</project>

```

There is no `compose-compiler` dependency.

**Comment by ZacSweers** [comment]
Respectfully, what you just said is misinformed. You seem to conflate the compiler dependency with other compose dependencies, so I will try to explain clearly.

> You add one plugin to your build script, it handles all other compose dependencies and is tied to the kotlin version ... It's one of the new things with Kotlin 2.0.
> Even though the library may not technically depend on the compose compiler by decoration, the resulting app will

This is incorrect. The compose compiler gradle plugin _only_ manages the compose compiler dependency. It does not affect _any other compose dependencies_. It effectively does two things:
1. Add the `org.jetbrains.kotlin:kotlin-compose-compiler-plugin` dependency to the appropriate compiler plugin classpath configurations.
2. Set up gradle dependency resolution strategies to force legacy versions from 1.x (i.e. the original androidx dependency and compose multiplatform dependency) to the new 2.x artifact.

It does not affect any other dependencies. A library compiled with compose-compiler 2.0.0 does not impose, say, compose-runtime 2.0 or 1.9.24.

> Coil V2 isn't compatible with Kotlin 2.0

Actually, it is. Kotlin supports n+1 minor release forward compatibility, even from 1.9 to 2.0. Not only that, compose is a stable API, which has infinite forward compatibility within the same major release. This point is also completely unrelated to the compiler plugin

---

The compose compiler plugin is versioned entirely independently of the compose runtime, and it largely does not care about the underlying runtime's version (barring minimums for new features, etc etc). At the time of writing, there is no such differences between compose-compiler 1.5.14 (targeting kotlin 1.9.24) and 2.0.0. They are functionally equivalent, and work with the same compose-runtime versions. This cutover parity was intentional to minimize migration friction.

With that all said, I'd like to ask that we bring this thread back to focus on the original request.

**Comment by mikepenz** [comment]
> > Will need to wait for a new alpha which supports recent compose versions.
> 
> Could you elaborate on what this support entails?

Thanks @ZacSweers for taking the time to answer the questions from the user yesterday (It appears all of them have been deleted though) 

The major problem appears to be a dependency version conflict

```
Execution failed for task ':multiplatform-markdown-renderer:compileDebugKotlinAndroid'.
> Error while evaluating property 'friendPathsSet$kotlin_gradle_plugin_common' of task ':multiplatform-markdown-renderer:compileDebugKotlinAndroid'.
   > Could not resolve all files for configuration ':multiplatform-markdown-renderer:debugCompileClasspath'.
      > Could not resolve org.jetbrains.compose.foundation:foundation:1.6.10.
        Required by:
            project :multiplatform-markdown-renderer
         > Cannot find a version of 'org.jetbrains.compose.foundation:foundation' that satisfies the version constraints:
              Dependency path 'com.mikepenz:multiplatform-markdown-renderer:0.20.0' --> 'org.jetbrains.compose.foundation:foundation:1.6.10'
              Constraint path 'com.mikepenz:multiplatform-markdown-renderer:0.20.0' --> 'org.jetbrains.compose.foundation:foundation:{strictly 1.6.0}' because of the following reason: version resolved in configuration ':multiplatform-markdown-renderer:debugRuntimeClasspath' by consistent resolution
              Dependency path 'com.mikepenz:multiplatform-markdown-renderer:0.20.0' --> 'io.coil-kt.coil3:coil-compose:3.0.0-alpha06' (releaseApiElements-published) --> 'io.coil-kt.coil3:coil-compose-android:3.0.0-alpha06' (releaseApiElements-published) --> 'io.coil-kt.coil3:coil-compose-core:3.0.0-alpha06' (releaseApiElements-published) --> 'io.coil-kt.coil3:coil-compose-core-android:3.0.0-alpha06' (releaseApiElements-published) --> 'org.jetbrains.compose.foundation:foundation:1.6.0'
```

at the time I was originally looking into it, I was traveling so it was much simpler to just release a version based on coil2 and one based on coil3 snapshot 

 Looking more, I could work-around this by adding exclude's to the coil dependency
 
 ```
    commonMainApi(libs.coil.core) {
        exclude("androidx.compose.foundation")
        exclude("androidx.compose.ui")
        exclude("org.jetbrains.compose.foundation")
    }
```

However, I feel like based on the last coil 3.x alpha there should be an updated version at some point. 

For now I feel like splitting coil2 vs coil3 makes probably sense, or possibly even better moving out coil into a different module all-together so no image loading is included by default at all.

**Comment by mikepenz** [comment]
Ah sorry got closed with the PR. 

Pulled out the coil dependency from core, so it doesn't get pulled in anymore by default.
So there's more flexibility, and you can theoretically use whichever image loader you prefer

**Comment by ZacSweers** [comment]
I'm still a little confused, what specific feature in coil3 is this depending on that's unreleased outside of snapshots? I use coil3 in my apps, so the artifact flexibility doesn't help much 😅

**Comment by mikepenz** [comment]
I am pretty sure it was `wasm`

**Comment by mikepenz** [comment]
I understand that this is currently a bit of a problem. But with the targets the lib currently offers, alpha06 would fail to compile for me. 

I can try to have a custom build for you published with alpha06 if that helps? Which targets do you need?

Alternative, with the coil3 now being a different artifact, the library won't ship with it anymore so it won't cause conflicts with you choosing alpha06, allowing you to provide the image loader implementation yourself for now.

These pieces are fully customizeable.


The following is all the code the coil3 module includes:
```
object Coil3ImageTransformerImpl : ImageTransformer {

    @Composable
    override fun transform(link: String): ImageData? {
        return rememberAsyncImagePainter(
            model = ImageRequest.Builder(LocalPlatformContext.current)
                .data(link)
                .size(coil3.size.Size.ORIGINAL)
                .build()
        ).let { ImageData(it) }
    }

    @Composable
    override fun intrinsicSize(painter: Painter): Size {
        var size by remember(painter) { mutableStateOf(painter.intrinsicSize) }

        if (painter is AsyncImagePainter) {
            LaunchedEffect(painter.state) {
                painter.state.painter?.let {
                    size = it.intrinsicSize
                }
            }
        }

        return size
    }
}
```

**Comment by ZacSweers** [comment]
I am not following, WASM has been available since Coil 3.0.0-alpha05. Alpha07 was just published as well: https://github.com/coil-kt/coil/blob/main/CHANGELOG.md#300-alpha07---june-26-2024.

**Comment by mikepenz** [comment]
Updated to use 3.0.0-alpha07. Will probably take around an hour to be available on maven central.

**Comment by ZacSweers** [comment]
Thanks!
