### ISSUE TITLE
How can I add modifier to Image?

### ISSUE THREAD

**Issue by agung-adhinata** [mikepenz/multiplatform-markdown-renderer#168]
## About this issue
I want to modify the image component to fill the width of the mobile screen regardless the size of the image. using `coil-compose:2.6.0`, I can achieve this by applying `Modifier.fillMaxWidth()` into `AsyncImage` component like:
```kotlin
AsyncImage(
  model = "https://picsum.photos/200/300" //or any image with size less than screen
  contentDescription = "Image", 
  modifier = Modifier.fillMaxWidth()
)
```

but for image link inside Markdown, I didn't find any documentation or issues that mention about this subject. I also found that `MarkdownParagraph` have `modifier` parameter and I can modify the component using `Modifier` like adding padding, etc. But this `modifier` parameter is seem non existent in `MarkdownImage` component.

I would really appreciate it if someone could lead me on the right path as I am _kinda_ lost to finding the solution.

## Details
- [x] Used library version - v0.21.0
- [x] Used platform - Android
- [x] Used support library version - N/A
- [x] Used gradle build tools version - 8.7
- [x] Used tooling / Android Studio version - Android Studio Koala | 2024.1.1
- [x] Other used libraries, potential conflicting libraries - Jetpack Compose only

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/multiplatform-markdown-renderer/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/multiplatform-markdown-renderer/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/multiplatform-markdown-renderer/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
Images are loaded using the `Image` in 2 different places. Either standalone or as part of a paragraph (inline images) 

- https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownImage.kt#L14-L23
- https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownText.kt#L134

The image is loaded with the information resolved from the `ImageTransformer` whereas the implementation depends on whichever usecase you have. Coil2, Coil3, Noop, ...

You can provide your own implementation by implementing the `ImageTransformer` and provide it to `Markdown`
```
 Markdown(
      MARKDOWN,
     imageTransformer = Coil3ImageTransformerImpl,           
)
```

The `ImageTransformer` has a `transform` function that return a `ImageData` exposing the ability to define the `Modifier`, and `Alignment` used for the `Image`. But also access to the `Content Description` and the painter.

**Comment by TimDeve** [comment]
Hello @mikepenz 👋 
Is there a way to make images scale to the width of the container if their intrisic size is smaller than the width of the container using just the modifier?

At the moment I hook into `intrisicSize` but it feels kinda hacky...

```kotlin
data class CustomImageTransformer(val maxSize: IntSize) : ImageTransformer {
    @Composable
    override fun transform(link: String): ImageData? {
        return Coil2ImageTransformerImpl.transform(link = link)?.copy(
            modifier = Modifier
                .fillMaxHeight()
                .fillMaxWidth()
        )
    }

    @Composable
    override fun intrinsicSize(painter: Painter): Size {
        val size = painter.intrinsicSize

        // If no size yet or it is a small image then don't scale
        if (size == Size.Unspecified || size.width < 256) {
            return Coil2ImageTransformerImpl.intrinsicSize(painter)
        }

        val ratio = maxSize.width.toFloat() / size.width
        val width = size.width * ratio
        val height = size.height * ratio
        return Coil2ImageTransformerImpl.intrinsicSize(painter)
            .copy(width = width, height = height)
    }
}
```

I

**Comment by mikepenz** [comment]
@TimDeve this is a tricky question. And I am afraid I don't have the specific answer. 

It's worth to note that you need to differentiate between images standalone, images as part of text (inline mages). 

A normal image is just the image itself as you can see here:
- https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownImage.kt#L17
So this should behave as any normal image

The inline image however is part of `InlineTextContent` which probably works different. It's again just an `Image` though: https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownText.kt#L134-L139

In both cases the the library doesn't do anything special with the `Image` itself

**Comment by TimDeve** [comment]
Thanks, appreciate it. As a Compose newbie I wasn't sure if I was missing something obvious.

**Comment by agung-adhinata** [comment]
Thanks @mikepenz for the answer, I'll try that method. But I think the readme should mention some additional information about this Image component for better understanding and visibilitity. 

I'll mark this as solved, I hoped that I have enough free time to experiment with this though.

**Comment by cod3licious** [comment]
@mikepenz I stumbled upon this issue when I got confused why my loaded images weren't rendered in their real size but instead fitted inside the placeholder space. It seems that the intrinsic size in the `Coil3ImageTransformerImpl` is not properly updated when an image is loaded. The following code should fix this and scale images to the full width of the container:
```kotlin
    @Composable
    override fun intrinsicSize(painter: Painter): Size {
        var size by remember(painter) { mutableStateOf(painter.intrinsicSize) }
        if (painter is AsyncImagePainter) {
            val painterState = painter.state.collectAsState()
            val intrinsicSize = remember { derivedStateOf { painterState.value.painter?.intrinsicSize } }
            LaunchedEffect(intrinsicSize.value) {
                size = intrinsicSize.value ?: return@LaunchedEffect
            }
        }

        return size
    }
```
The main problem in the original code is that the `LaunchedEffect` is called on the painter state and not its value, which means it is not called again when the value itself is updated. Since the painter itself can change more often, the `LaunchedEffect` in the new code is only called on the `intrinsicSize` to avoid needless updates.

**Comment by mikepenz** [comment]
@cod3licious thank you for the comment and suggestion above. I actually believe we can drop launchedEffect alltogether now given the state is collected as state in coil3. 

Can you please check the following code: https://github.com/mikepenz/multiplatform-markdown-renderer/pull/201/files ?

**Comment by cod3licious** [comment]
Ahh great, even simpler. However, we should keep the `derivedStateOf` to prevent unnecessary recompositions (you can see this when you put a log message before the return statement - with your new code it is basically stuck in a recomposition loop). So this should work:
```kotlin
val intrinsicSize by remember { derivedStateOf { (painterState.value.painter?.intrinsicSize) } }
intrinsicSize?.also { size = it }
```
