### ISSUE TITLE
SelectionContainer clipboard erasing newline chars

### ISSUE THREAD

**Issue by Melodeiro** [mikepenz/multiplatform-markdown-renderer#178]
## About this issue

When using `SelectionContainer`, clipboard behaviour works not as expected. Copied text ends with newline characters erased. I guess because of component is being composed by different sub-components. Earlier i used invisible symbols (which i added with `replace("\n", ...)` function) as a workaround with `ClipboardManager` provided with `CompositionLocalProvider`, but now its not possible because latest versions got more complex parsing strategies.

Probably that is possible to do with custom components, but im going to ask you, maybe you will consider adding support for clipboard out of the box?

## Details
Version 0.22.0
Jvm platform

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/multiplatform-markdown-renderer/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/multiplatform-markdown-renderer/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/multiplatform-markdown-renderer/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
That is quite an interesting one. Personally I feel like this should be something the `SelectionContainer` is meant to handle, as this seems like a very common usecase to select content across multiple composeables. 

I don't think it is going to be maintainable to hack it together in some way though 🤔

**Comment by mikepenz** [comment]
Looked more into this. This is default behavior from Compose. And does not appear to be a bug in this project. 

Explore this example: 
https://developer.android.com/develop/ui/compose/text/user-interactions#select-text

<img width="913" alt="Screenshot 2024-08-23 at 16 00 28" src="https://github.com/user-attachments/assets/d717599a-9c11-4890-9aa6-a321a3d1c3a6">

Having the same behavior

**Comment by Azadios** [comment]
Hello @mikepenz and thank you for maintaining this great library!

Sorry for reviving this old thread, but I'm a bit confused on what to do about this.

I understand why different composables within one SelectionContainer are copied without newline at the end, it's most obvious if in the example from compose you switch Column to Row. Nothing says that adding newline at the end of each separate text upon copy is a correct behavior, it's kind of an illusion created by Column in the example.
And I agree that it makes most sense to add such control to something from compose (probably not SelectionContainer as it can contain both Column and Row I would expect them to behave differently within the same SelectionContainer)

Now there's another side of this issue. I have a big chunk of text which contains newlines. If I am to use single Text composable, then those newlines are copied just fine. When I switch to using Markdown composable - it splits my single continuous text into separate composables and therefore changes the behavior of SelectionContainer.
I understand why it seems as not a bug from a library developer perspective, but it sure feels like a bug that this library introduces if I'm on the user side.

So my question is - is there any way I can control this behavior? Is there any way I can at least hack this on my side? How can I know at which positions markdown renderer decided to split the copied text into separate blocks effectively removing newlines?

**Comment by Azadios** [comment]
Hey @mikepenz! Thanks for a quick reply.

Yeah, it seems there's no workaround for this and there are [numerous bugs and feature requests](https://issuetracker.google.com/issues?q=status:open%20componentid:779818%20SelectionContainer) for compose asking to create a developer API for this.

Most notably [this one](https://issuetracker.google.com/issues/142551575) which is nearly 6 years old. Seems that compose is not mature enough for this :)

Anyways, I appreciate your time!

**Comment by Azadios** [comment]
Interesting...
CMP 1.9.0 indeed gives me newlines between composables. And what's funny is that it adds newline even between Texts in Row, so I guess they've fallen for the illusion I've described above :)

>  So finally google/jetbrains fixed it i guess

Not sure about Jetpack Compose, but this is indeed something that is changed in CMP 1.9.0, so I've created a bug ticket for the Row case [CMP-9020](https://youtrack.jetbrains.com/issue/CMP-9020) SelectionContainer adds newlines between multiple Text in Row

There's one more issue with 1.9.0 though - [CMP-8874](https://youtrack.jetbrains.com/issue/CMP-8874) ComposeViewport copy hotkey is not working
This defeats the purpose for me, but if you're not concerned that much about Linux Web (I believe it works on other OS and platforms) then I'd say go for it.

And thanks for sharing @Melodeiro, I appreciate it 👍
