### ISSUE TITLE
How to display xml text

### ISSUE THREAD

**Issue by keta1** [mikepenz/multiplatform-markdown-renderer#181]
## How to display xml text

I want to show the text, how to prevent parsing of xml

```
aaaaa

<resources>
  <string name="japanese">日本語</string>
</resources>
```
![telegram-cloud-photo-size-5-6107018899196330284-y](https://github.com/user-attachments/assets/3206e60d-de16-4f64-8bc7-200da1c8d849)

## Details
Used library version: 0.24.0
## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/multiplatform-markdown-renderer/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/multiplatform-markdown-renderer/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/multiplatform-markdown-renderer/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/MIGRATION.md)

**Comment by chokokatana** [comment]
This is a markdown issue, if you go to https://spec.commonmark.org/dingus/ and paste your markdown code you will get no XML rendered, because tags are passed through. You can see this with the web inspector, but obviously can't on android. You could modify the code to use triple backticks:

![mk](https://github.com/user-attachments/assets/a8a7f962-194a-4453-9bcc-1b583916f03f)

**Comment by mikepenz** [comment]
Thank you for answering this issue @chokokatana really appreciate the help!

**Comment by keta1** [comment]
> Thank you for answering this issue @chokokatana really appreciate the help!
> 
> @keta1 please close the issue as this is not a bug of the library.
> 
> If you wrap the code in ``` it will work as expected
> 
> ```
> ```
> <resources>
>   <string name="japanese">日本語</string>
> </resources>
> ```
> ```

But actually I can't decide what text that need to display

**Comment by keta1** [comment]
Is there any better solution?

**Comment by mikepenz** [comment]
As @chokokatana highlighted here: https://github.com/mikepenz/multiplatform-markdown-renderer/issues/181#issuecomment-2238925538 this is a markdown issue / behavior. 

To have such blocks shown as code, wrapping it in a code block appears to be the best solution.

**Comment by keta1** [comment]
> As @chokokatana highlighted here: [#181 (comment)](https://github.com/mikepenz/multiplatform-markdown-renderer/issues/181#issuecomment-2238925538) this is a markdown issue / behavior.
> 
> To have such blocks shown as code, wrapping it in a code block appears to be the best solution.

Thank you for your answer, I will try to solve this problem

**Comment by chokokatana** [comment]
> Thank you for your answer, I will find a way to solve this problem in a special way

It's not just xml code you need to escape, if you want to display gpt output "safely" you also need to care about how to format links, italics, etc. You just have entered the hell that is format escaping of one tool's output into another tool's input.

**Comment by keta1** [comment]
> > Thank you for your answer, I will find a way to solve this problem in a special way
> 
> It's not just xml code you need to escape, if you want to display gpt output "safely" you also need to care about how to format links, italics, etc. You just have entered the hell that is format escaping of one tool's output into another tool's input.

![telegram-cloud-photo-size-5-6107018899196330385-y](https://github.com/user-attachments/assets/ad51f7a9-d2d6-4976-a20e-6bde2253077a)
I've found too many display issues
