### ISSUE TITLE
Custom link handler

### ISSUE THREAD

**Issue by chokokatana** [mikepenz/multiplatform-markdown-renderer#182]
## About this issue

I don't see any mechanism through which I can handle link clicking by myself, links open by default in an external browser but I'd like to handle them myself.

## Details
- [X] Used library [0.24.0](https://github.com/mikepenz/multiplatform-markdown-renderer/releases/tag/v0.24.0)
- [X] Kmp

## Checklist

- [X] Searched for [similar issues](https://github.com/mikepenz/multiplatform-markdown-renderer/issues)
- [X] Checked out the [sample application](https://github.com/mikepenz/multiplatform-markdown-renderer/tree/develop/app)
- [X] Read the [README](https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/README.md)
- [X] Checked out the [CHANGELOG](https://github.com/mikepenz/multiplatform-markdown-renderer/releases)
- [ ] Read the [FAQ](https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/FAQ.md)

FAQ file doesn't exist any more.

**Comment by mikepenz** [comment]
Good day. 

The library uses the `LocalUriHandler.current` to open the URL. This defaults to open in a browser on android:
https://github.com/mikepenz/multiplatform-markdown-renderer/blob/6f04f9745009f47d0fca27c4952123f07bfe9f55/multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownText.kt#L98

You can provide your own handler via the [CompositionLocal](https://developer.android.com/develop/ui/compose/compositionlocal)

**Comment by chokokatana** [comment]
Oof, that's so hidden.
