### ISSUE TITLE
Can't build iOS after adding markdown renderer dependency

### ISSUE THREAD

**Issue by chokokatana** [mikepenz/multiplatform-markdown-renderer#189]
## About this issue

After adding the line `implementation("com.mikepenz:multiplatform-markdown-renderer:0.25.0")` to my sourceSets, commonMain block, iOS stops building with the error:

```
> Task :xcodeVersion UP-TO-DATE
> Task :KmmLocations:checkKotlinGradlePluginConfigurationErrors
> Task :KmmLocations:generateCommonMainDatabaseInterface UP-TO-DATE
> Task :KmmLocations:generateComposeResClass UP-TO-DATE
> Task :KmmLocations:generateIosMainNonAndroidBuildConfig SKIPPED
> Task :KmmLocations:generateIosSimulatorArm64MainNonAndroidBuildConfig SKIPPED
> Task :KmmLocations:generateNonAndroidBuildConfig

> Task :KmmLocations:kspKotlinIosSimulatorArm64 FAILED
error: Could not find "androidx.lifecycle:lifecycle-common" in [/Users/gradha/project/geodb/wallace-kmm-locations, /Users/gradha/.konan/klib, /Users/gradha/.konan/kotlin-native-prebuilt-macos-aarch64-1.9.23/klib/common, /Users/gradha/.konan/kotlin-native-prebuilt-macos-aarch64-1.9.23/klib/platform/ios_simulator_arm64]
error: Compilation finished with errors
```

No other changes are necessary for the build to fail. Android build works fine. Removing the line makes iOS compile and run on simulator again.

## Details
- Used library version 0.25.0
- Used platform iOS
- Kotlin compiler extension 1.5.11
- Gradle 8.2
- Android Studio 2023.3.1 Patch 2
- Compose 1.6.2
- Kotlin 1.9.23
- AGP 8.2.2

**Comment by mikepenz** [comment]
Based on maven central those dependencies should have ios related versions:

https://mvnrepository.com/artifact/androidx.lifecycle?p=2

<img width="688" alt="Screenshot 2024-07-26 at 08 49 55" src="https://github.com/user-attachments/assets/a7cf954c-f5b6-445d-9058-590e8c35cd17">

**Comment by mikepenz** [comment]
If you add `androidx.lifecycle:lifecycle-common` to your project, will it resolve the problem?

**Comment by chokokatana** [comment]
Tried reproducing the problem and can't any more. Since then I've moved gradle to a hierarchical setup and upgraded lifecycle-runtime-compose to 2.8.4, so maybe some of that improved the situation.
