### ISSUE TITLE
Update Usage Docs

### ISSUE THREAD

**Issue by cesards** [mikepenz/multiplatform-markdown-renderer#192]
## About this issue

- Usage section in the main page seems legacy

After pulling the library for the first time, I checked [the docs](https://github.com/mikepenz/multiplatform-markdown-renderer#usage) and they don't match the actual implementation. So from the docs perspective, using the library should be as easy as just passing a simple string:
```
val markdown = """
### What's included 🚀

- Super simple setup
- Cross-platform ready
- Lightweight
""".trimIndent()

Markdown(markdown)
```
But the actual implementation (0.25.0 for Android) is asking us to provide colors and typography (the rest of input parameters have defaults)
```
fun Markdown(
    content: String,
    colors: MarkdownColors,
    typography: MarkdownTypography,
    ....
)
```

Would it make sense to update the docs? and maybe provide minimum guidance around using default markdown color and typography?

Thanks in advance!

**Comment by mikepenz** [comment]
Oh that's a great observation. You require to have either the m2 or m3 module in addition for this simple integration.
https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/multiplatform-markdown-renderer-m3/src/commonMain/kotlin/com/mikepenz/markdown/m3/Markdown.kt#L25

This changed when we removed any material reference from the base library

**Comment by mikepenz** [comment]
I hope that clarifies it. If you have additional suggestions on how to further clarify this I'd love to hear your feedback.
