### ISSUE TITLE
Customize header element with MarkdownComponent

### ISSUE THREAD

**Issue by gs-ts** [mikepenz/multiplatform-markdown-renderer#200]
## About this issue

Here I am again with another simple issue which I have been stuck all day...

I am trying to style a `heading2` with text align in center and a different color. 
So let's say we have the following markdown example:

```
val markdownExample = """
                      ## What's included
                      
                      - Super simple setup
                      - Cross-platform ready
                      - Lightweight
                      """.trimIndent()

val customHeading2: MarkdownComponent = {
    val styledText = buildAnnotatedString {
        pushStyle(LocalMarkdownTypography.current.h2.toSpanStyle().copy(color = Color.Red))
        buildMarkdownAnnotatedString(it.content, it.node)
        pop()
    }

    Text(
        styledText,
        modifier = Modifier.fillMaxSize(),
        textAlign = TextAlign.Center
    )
}

Markdown(
    content = markdownExample.trimIndent(),
    colors = markdownColor(),
    typography = markdownTypography(),
    components = markdownComponents(heading2 = customHeading2)
)
```

However, this disappears completely the heading from the content. 
Isn't the `LocalMarkdownTypography.current.h2` the one that we need to customize?

## Details
- Library version: `com.mikepenz:multiplatform-markdown-renderer-m3:0.25.0`
- Platform: Android
- IDE: Android Studio

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/multiplatform-markdown-renderer/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/multiplatform-markdown-renderer/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/multiplatform-markdown-renderer/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/MIGRATION.md)

**Comment by gs-ts** [comment]
I am also trying with `markdownAnnotator` but doesn't work either 😕 

```
 markdownAnnotator { content, child ->
     if (child.type == GFMElementTypes.HEADER) {
          ....
     }
```

**Comment by mikepenz** [comment]
@gs-ts you are already pretty close, however the code on how to retrieve the content is not yet correct. 

The library exposes the same structure as the markdown library parses, as such the correct node needs to be used. 
You can see how a default header is implemented here: https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownHeader.kt#L20-L28

Putting this in action in your case will look like:
```
val customHeading2: MarkdownComponent = {
    val content = it.content
    it.node.findChildOfType(MarkdownTokenTypes.ATX_CONTENT)?.let {
        val styledText = buildAnnotatedString {
            pushStyle(LocalMarkdownTypography.current.h2.toSpanStyle().copy(color = Color.Red))
            buildMarkdownAnnotatedString(content, it)
            pop()
        }
        Text(
            styledText,
            modifier = Modifier.fillMaxSize(),
            textAlign = TextAlign.Center
        )
    }
}
```
<img width="912" alt="Screenshot 2024-08-30 at 09 26 02" src="https://github.com/user-attachments/assets/d22edd53-e3a3-4723-9ead-6a9d8b84fdbc">

**Comment by gs-ts** [comment]
that was quite tricky for me... But I understood it. Thank you very much!

One more (hopefully last) question. Now I am trying to apply styling on links. I saw your reply here, and I tried it but it breaks the markdown syntax and it's not clickable anymore.

```
    Markdown(
        modifier = Modifier
            .fillMaxSize()
            .padding(),
        typography = markdownTypography(
            text = CustomTheme.typography.body2Regular,
            h2 = CustomTheme.typography.title
        ),
        content = markdownContent,
        components = markdownComponents(
            heading2 = customHeading2
        ),
        annotator = markdownAnnotator { content, child ->
            if (child.type == INLINE_LINK) {
                val targetNode = child.children.firstOrNull {
                    it.type.name == AUTOLINK.name
                } ?: child
                val destination = targetNode.getTextInNode(content).toString()
                pushStringAnnotation(MARKDOWN_TAG_URL, (destination))
                pushStyle(
                    SpanStyle(
                        color = Color.Red,
                        textDecoration = TextDecoration.Underline,
                        fontWeight = FontWeight.Bold
                    )
                )
                append(destination)
                pop()
                true
            } else false
        }
    )
```

So I get something like this on the screen "[More about it] (https://www.moreabout.it)"
