### ISSUE TITLE
No interface method startReplaceGroup(I)V in class Landroidx/compose/runtime/Composer; or its super classes

### ISSUE THREAD

**Issue by lukaszkn** [mikepenz/multiplatform-markdown-renderer#211]
I'm using m2 renderer. 
```
implementation("com.mikepenz:multiplatform-markdown-renderer:0.27.0-b02")
implementation("com.mikepenz:multiplatform-markdown-renderer-m2:0.27.0-b02")
```
I'm placing Markdown in the view but I get runtime exception below. Could you help? In version 0.26.0 it works fine
```
FATAL EXCEPTION: main
java.lang.NoSuchMethodError: No interface method startReplaceGroup(I)V in class Landroidx/compose/runtime/Composer; or its super classes (declaration of 'androidx.compose.runtime.Composer' appears in /data/app/~~3akpHAMbiNKTNv_ROs7jxQ==/com.x.xxx-ntT4sua5hlKsNdHfAlh1eg==/base.apk!classes11.dex)
    at com.mikepenz.markdown.m2.MarkdownColorsKt.markdownColor-69fazGs(Unknown Source:5)
    at com.mikepenz.markdown.m2.MarkdownKt.Markdown(Markdown.kt:26)
```

**Comment by mikepenz** [comment]
@lukaszkn which version of compose are you using?

0.27.0-b02 requires compose 1.7.0 

https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/gradle/libs.versions.toml#L8-L9

**Comment by lukaszkn** [comment]
I was using `compose-bom 2024.06.00`. Upgraded and now it works fine. Thanks for your help.

**Comment by albertaleksieiev** [comment]
> @lukaszkn which version of compose are you using?
> 
> 0.27.0-b02 requires compose 1.7.0
> 
> https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/gradle/libs.versions.toml#L8-L9

Faced with this issue on iOS (startReplaceGroup), fixed by updating compose, thx to your suggestions.

So I have in `libs.versions.toml`
```
compose = "1.7.3"
compose-plugin = "1.7.0-beta02"
```
