### ISSUE TITLE
[FEATURE] Markdown editor + export

### ISSUE THREAD

**Issue by Maandraj** [mikepenz/multiplatform-markdown-renderer#214]
It works great (At least on Android)

 I thought it would be great to add an editor and export. 
 For example, there is - https://github.com/MohamedRejeb/Compose-Rich-Editor. But it still works crookedly
 
 Thanks !

**Comment by mikepenz** [comment]
This libraries focus is only the rendering. A WYSIWYG editor is out of scope for the library itself. 

Thank you for the suggestion.
