### ISSUE TITLE
Replace bullets in list with image icons.

### ISSUE THREAD

**Issue by aegis123** [mikepenz/multiplatform-markdown-renderer#216]
## About this issue

I was looking how to replace the bullets in lists with a custom icon like a checkmark which would be an actual image instead of a String or an character

Currently we are using compose-richtext which is supposed to be multiplatform but only supports Android/Desktop, and im looking for multiplatform also to IOS and Web. 

That library offers something like this

```kotlin
fun checkMarkUnorderedListStyle() =
    ListStyle(
        contentsIndent = 8.sp,
        unorderedMarkers = {
            object : UnorderedMarkers {
                @Composable
                override fun drawMarker(level: Int) {
                    Icon(
                        imageVector = CheckmarkThick,
                        tint = Color.Green,
                        contentDescription = null,
                        modifier = Modifier.size(20.dp),
                    )
                }
            }
        },
    )
```

Which then can be added to the RichText composable with the RichTextStyle. The current approach in this library seems somewhat similar but uses CompositonLocalProvider to offer a BulletHandler to change the character of the bullet but it would be nice if we could also replace it with a composable or maybe a annotatedString/SpannableString.

## Details
- [x] Used library version
   0.26.0
- [x] Used platform
   Android
- [x] Used support library version
- [x] Used gradle build tools version
   8.9
- [x] Used tooling / Android Studio version
- [x] Other used libraries, potential conflicting libraries
   [Compose Richtext](https://halilibo.com/compose-richtext/)

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/multiplatform-markdown-renderer/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/multiplatform-markdown-renderer/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/multiplatform-markdown-renderer/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/MIGRATION.md)

**Comment by aegis123** [comment]
Figured out how to do it with a custom `MarkdownComponent` which replaces the default `unorderedList MarkdownComponent` in the `MarkdownComponents`

**Comment by mikepenz** [comment]
Sorry for not answering, last few weeks were busy. 

Would you be so kind to open a PR to add it as a sample perhaps? or a snippet so others can benefit from it?

**Comment by aegis123** [comment]
added a PR #218
