### ISSUE TITLE
Wrong text escaping

### ISSUE THREAD

**Issue by keta1** [mikepenz/multiplatform-markdown-renderer#221]
## About this issue
https://github.com/mikepenz/multiplatform-markdown-renderer/blob/4c2fedb26b38b4fda3d6c4f3db4bac9454e389e6/multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/utils/Extensions.kt#L43-L46

https://github.com/JetBrains/markdown/blob/43c06cb6a9d66caab8b431f738aba3c57aee559f/src/commonMain/kotlin/org/intellij/markdown/html/entities/EntityConverter.kt#L7-L12

EntityConverter.replaceEntities will process text incorrectly and escape some content that does not need to be escaped.

This [change ](#213)seems to have been introduced to unescape certain text, but as it stands now it looks like we need to implement a separate EntityConverter

**Comment by mikepenz** [comment]
Thank you for the issue. 

Do you have some examples where this is a problem? Given we use the official API from the markdown library, I'd expect it to work as expected 🤔

**Comment by keta1** [comment]
> Thank you for the issue.
> 
> Do you have some examples where this is a problem? Given we use the official API from the markdown library, I'd expect it to work as expected 🤔

This API is only designed for web pages and is not applicable in compose.
For example, it will escape `&` into `&amp;`

**Comment by mikepenz** [comment]
Thanks for the example!
