### ISSUE TITLE
Not possible to click on www.something.com in markdown text

### ISSUE THREAD

**Issue by joeldenke-paf** [mikepenz/multiplatform-markdown-renderer#231]
## About this issue

- Markdown renderer autodetecting www.something.com when being plain text as clickable link. However LocalUriHandler does not accept www.something.com as valid url, and get exception. Missing a way to handle this autolink things or that library automatic support this.
- To reproduce, have any www.something.com as regular text, make sure its not markdown url format.

## Details
- [ ] Version 0.27.0 (Same in all versions)
- [ ] Android

**Comment by mikepenz** [comment]
I'd argue this is out of scope for the library itself, as the url handling is solely in the responsibility of the `UriHandler` 

you can provide your own uri handler implementation handling such strings. 

Here's the default Android implementation

```
class AndroidUriHandler(private val context: Context) : UriHandler {

    /**
     * Open given URL in browser
     *
     * @throws IllegalArgumentException when given [uri] is invalid and/or can't be handled by the
     * system
     */
    override fun openUri(uri: String) {
        try {
            context.startActivity(Intent(Intent.ACTION_VIEW, Uri.parse(uri)))
        } catch (e: ActivityNotFoundException) {
            throw IllegalArgumentException("Can't open $uri.", e)
        }
    }
}

```

**Comment by mikepenz** [comment]
https://github.com/JetBrains/markdown is used under the hood for the parsing of the nodes. 

With
- https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/utils/AnnotatedStringKtx.kt#L129
- https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/utils/AnnotatedStringKtx.kt#L136

handling the AUTOLINK node types.


You can provide a custom annotator to replace how auto links are interpreted:

```
Markdown(
    MARKDOWN,
    annotator = markdownAnnotator { content, child ->
        fun ASTNode.getUnescapedTextInNode(allFileText: CharSequence): String {
            val escapedText = getTextInNode(allFileText).toString()
            return EntityConverter.replaceEntities(
                escapedText,
                processEntities = false,
                processEscapes = true
            )
        }

        when (child.type) {
            MarkdownElementTypes.AUTOLINK -> {
                append(child.getUnescapedTextInNode(content))
                true
            }

            GFMTokenTypes.GFM_AUTOLINK -> {
                append(child.getUnescapedTextInNode(content))
                true
            }

            else -> false
        }
    },
    ...
)
```

**Comment by joeldenke-paf** [comment]
Hehe right, yeah that was my first attempt try but failed find in sample or documentation how to do that with annotations. Thanks, for now I think the handling at UriHandler level is the most accurate. But okay, I guess we can close this then, even though it feels strange that the library doing this, feels like outside of Markdown protocol and more Android specifik autolink but maybe I am wrong, not sure.
