### ISSUE TITLE
Using this in a pure JVM desktop project  and got a render error

### ISSUE THREAD

**Issue by GoldTest** [mikepenz/multiplatform-markdown-renderer#233]
log:

Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError: 'void androidx.compose.runtime.Composer.startReplaceGroup(int)'
	at com.mikepenz.markdown.model.MarkdownPaddingKt.markdownPadding-Jo9jhoo(MarkdownPadding.kt)
	at com.mikepenz.markdown.compose.MarkdownKt.Markdown(Markdown.kt:41)

only got 
    @ComposeCompilerApi
    fun startReplaceableGroup(key: Int)
in the Composer class,didnot see the startReplaceGroup.

Anyone help?

**Comment by mikepenz** [comment]
This project uses Compose-Multiplatform 1.7.0. Please make sure your project uses the same version.

- https://github.com/mikepenz/multiplatform-markdown-renderer/releases/tag/v0.27.0

**Comment by royneely** [comment]
Running on JVM environment and was getting this error with compose 1.7.0 and 0.35.0 of this library. Fixed by downgrading this library to 0.27.0. Just in case anyone else gets the same error on JVM with v0.35.0, can be fixed by downgrading.

**Comment by mikepenz** [comment]
0.34.0 and onwards uses compose 1.8.0: https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/MIGRATION.md#version-0340
