### ISSUE TITLE
How to customize italic rendering?

### ISSUE THREAD

**Issue by arthef** [mikepenz/multiplatform-markdown-renderer#241]
## About this issue

Is it possible to customize how italic text is displayed? For example, I would like to use a different/smaller font for italic text.

I cannot find any example, I guess this might be a custom component but I cannot figure it out. Any pointers would be very much appreciated.

**Comment by mikepenz** [comment]
Italic is part of the string annotator. As its a style applied onto text in paragraphs: 
https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/utils/AnnotatedStringKtx.kt#L97-L101

You can use the `markdownAnnotator()` to provide your own custom handling for that type.

E.g. push different style, ... for text within a `EMPH` section

**Comment by arthef** [comment]
I have not gone this route because, custom paragraph handling solved my issues.
