### ISSUE TITLE
Custom paragraph handling

### ISSUE THREAD

**Issue by arthef** [mikepenz/multiplatform-markdown-renderer#242]
## About this issue

Is it possible to have different typography for different paragraphs? I mean similar to quote paragraph. I would like to define a few more types of paragraphs, like “comment”, “translation”, etc… I can mark start of the paragraph with different symbols and I would like to be able to customize how they are displayed.

Is it possible to do so using custom components or some other API? Any pointers or code sample would be very useful.

Thank you

**Comment by mikepenz** [comment]
Good day.

Please see the `Advanced Usage` section in the README

Not only can you modify annotation handling but you can also have custom components: 
https://github.com/mikepenz/multiplatform-markdown-renderer?tab=readme-ov-file#custom-components

I'd advice you to look into the `markdownComponents()` and `markdownAnnotator()` APIs:
https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/Markdown.kt#L45-L47

**Comment by arthef** [comment]
Thank you for responding. I have already read entire README and specifically the section on custom paragraph component and example. However it is still not clear to me how to implement custom handling for different paragraph types. For example based on the first character of the paragraph.

Do you know of any code examples I could look at?

**Comment by mikepenz** [comment]
No example for this specific scenario you are trying to achieve as it's quite outside of the normal usecase. 

However if you look here this is how the paragraph component is provided within the lib: https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/components/MarkdownComponents.kt#L169-L171

You would need to implement your own custom paragraph, expanding on how paragraphs are handled by default:

https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownParagraph.kt#L11-L29

Likely requiring your own custom annotated string building to style it to the way you want: 
https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownParagraph.kt#L18-L22

**Comment by arthef** [comment]
I was able to find a solution, thanks to your comments.
