### ISSUE TITLE
customParagraphComponent example prevents links to be clickable

### ISSUE THREAD

**Issue by arthef** [mikepenz/multiplatform-markdown-renderer#243]
The example works great and thanks to it I was able to customize rendering of markdown in my app.

Unfortunately this example also prevents links to be clickable. I understand that this has something to do with using `Text` composable in the example. However, I cannot find any hints or guide on how to keep the links to be clickable with the custom paragraph component.

My guess is that somehow I should detect if the processed text contains link and then use a different composable? Please advise.

**Comment by mikepenz** [comment]
Links and other styling within a paragraph is handled by the annotator. 

the function in the library responsible for making a span in an annotated string clickable is here: https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/utils/AnnotatedStringKtx.kt#L21-L40

**Comment by arthef** [comment]
Thank you for your response and pointing me to the code. In my case the solution was very simple. I just replaced in your custom component example `Text()` with `MarkdownText` and links became clickable.
