### ISSUE TITLE
![Image](ImageURL) rendered by PARAGRAPH

### ISSUE THREAD

**Issue by BreimerR** [mikepenz/multiplatform-markdown-renderer#34]
## About this issue
```ASTNode.handleElement``` for ![Image](Image URL's) section are handled by a paragraph and not   ```MarkdownElementTypes.IMAGE```
This is causing images to appear with a fixed size of 180.dp since Placeholders aren't supporting flexibility here.

## Details
- [ ]  0.2.4
- [ ] Android, Desktop(Linux)
- [ ] 7.0.4
- [ ] IDEA-U

**Comment by mikepenz** [comment]
@BreimerR thank you for the report. 

I would love to improve that but haven't found the right compose API yet to achieve having the image larger

**Comment by BreimerR** [comment]
Yeah just saw that from the compose side played around with it a bit nothing fits yet. Maybe if the parser broke it down to IMAGE type first then something might work but that would not support for some cases. i.e badges in paragraphs

**Comment by mikepenz** [comment]
I believe this may be handled now after https://github.com/mikepenz/multiplatform-markdown-renderer/pull/72 was introduced
