### ISSUE TITLE
Markdown-it  flavour

### ISSUE THREAD

**Issue by CarlosEsco** [mikepenz/multiplatform-markdown-renderer#48]
Would love a flavor that is configurable with html tags.  Notice ```[test <test>](https://test.com/)``` actually rendering the <test> in the output.

[sample](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%23%23%20Links%5Cn%5Cn%5Blink%20text%5D%28http%3A%2F%2Fdev.nodeca.com%29%5Cn%5Cn%5Blink%20with%20title%5D%28http%3A%2F%2Fnodeca.github.io%2Fpica%2Fdemo%2F%20%5C%22title%20text!%5C%22%29%5Cn%5Cn%5Btest%20%3Ctest%3E%5D%28https%3A%2F%2Ftest.com%2F%29%5Cn%5CnAutoconverted%20link%20https%3A%2F%2Fgithub.com%2Fnodeca%2Fpica%20%28enable%20linkify%20to%20see%29%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Atrue%2C%22_view%22%3A%22html%22%7D%7D)

**Comment by mikepenz** [comment]
This library uses https://github.com/JetBrains/markdown to parse the markdown. I don't think they currently offer any other flavour beyond what is noted here: https://github.com/JetBrains/markdown/tree/master/src/commonMain/kotlin/org/intellij/markdown/flavours

Given that parsing is not handled by this library I'll close this ticket. 

Maybe you can contribute a different flavour to the main markdown library in use
