### ISSUE TITLE
Add JS support

### ISSUE THREAD

**Issue by Ayfri** [mikepenz/multiplatform-markdown-renderer#55]
## About this issue

- Briefly describe the issue

- How can the issue be reproduced / sample code
Hi, I'm using Compose for Web as a `kotlin("js")` project and I installed the library in multiplatform, but I still can't use it in my project, I'm in Compose `1.2.0-apha01-dev753` using Kotlin `1.7.0` with Gradle `7.5.0` and the library in `0.6.1` with Intellij 2022.2.

## Checklist

- [X] Searched for [similar issues](https://github.com/mikepenz/multiplatform-markdown-renderer/issues)
- [X] Checked out the [sample application](https://github.com/mikepenz/multiplatform-markdown-renderer/tree/develop/app)
- [X] Read the [README](https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/README.md)
- [X] Checked out the [CHANGELOG](https://github.com/mikepenz/multiplatform-markdown-renderer/releases)
- [X] Read the [FAQ](https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/FAQ.md)
- [X] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
Currently there is no support for `kotlin('js')` just for JVM and Android. 

https://github.com/mikepenz/multiplatform-markdown-renderer#setup


Would be interesting to see if somebody would like to contribute JS support.

**Comment by mikepenz** [comment]
Unfortunately this is currently still not possible as the `org.jetbrains:markdown` does not offer a wasm variant

**Comment by Melodeiro** [comment]
Just created [an issue](https://github.com/JetBrains/markdown/issues/140) at JB markdown repo

**Comment by joreilly** [comment]
JB markdown library just got Kotlin/Wasm support! https://github.com/JetBrains/markdown/issues/140

**Comment by mikepenz** [comment]
Thanks! Saw it already and awaiting the release to be available🎉

**Comment by mikepenz** [comment]
Unfortunately it seems the 0.7.0 release is not yet synced to maven central. Need to be a bit more patient :D

**Comment by mikepenz** [comment]
The wasm target was added in 0.14.0. Sonatype seems a bit slow right now. so syncing might take a while, but the staging repo is closed. 🥳
