### ISSUE TITLE
Feature: Allow to use custom components.

### ISSUE THREAD

**Issue by pbit** [mikepenz/multiplatform-markdown-renderer#57]
## About this issue

It would be nice if I could use my own components for rendering.

## Use Cases:

- Render only a subset of components (e.g. only headings for a table of contents)
- Decorate a component (e.g. add a "copy to clipboard" button to code)
- Add custom logic (e.g. resolve relative URLs in links anmd images)

**Comment by CarlosEsco** [comment]
This would be super helpful since you can't handle relative urls at all currently

**Comment by mikepenz** [comment]
Thanks @pbit for the PR adding this functionality
