### ISSUE TITLE
NoSuchMethodError thrown using newer GFM versions

### ISSUE THREAD

**Issue by ZacSweers** [mikepenz/multiplatform-markdown-renderer#61]
## About this issue

When running `Markdown()` with a newer version of intellij's markdown dependency (`0.4.1`), the following error occurs at runtime

```
Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError: org.intellij.markdown.flavours.gfm.GFMFlavourDescriptor: method 'void <init>(boolean, boolean, int, kotlin.jvm.internal.DefaultConstructorMarker)' not found
	at com.mikepenz.markdown.MarkdownKt.Markdown(Markdown.kt:66)
	at dev.zacsweers.ComposableSingletons$DesktopKt$lambda-1$1.invoke(Desktop.kt:30)
	at dev.zacsweers.ComposableSingletons$DesktopKt$lambda-1$1.invoke(Desktop.kt:17)
```

## Details
- Used library version - `0.6.1`
- Used platform - Desktop
- Used gradle build tools version - `8.3-rc-3`
- Used tooling / Android Studio version - IntelliJ
- Other used libraries, potential conflicting libraries - `clikt`, which brings in a newer markdown dep version

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/multiplatform-markdown-renderer/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/multiplatform-markdown-renderer/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/multiplatform-markdown-renderer/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
Thank you for the report. I will look into it.

**Comment by Abhay-cloud** [comment]
@mikepenz Hey, on v0.6.1 it is working well. But when I tried to use v0.7.1 I got NoSuchMethodError.

**Comment by mikepenz** [comment]
@Abhay-cloud what `NoSuchMethodError` do you see. 

0.7.1 also retrieved an update of compose: https://github.com/mikepenz/multiplatform-markdown-renderer/releases/tag/v0.7.1
