### ISSUE TITLE
Use Kamel for image loading 

### ISSUE THREAD

**Issue by psuzn** [mikepenz/multiplatform-markdown-renderer#70]
## About this issue

I know `coil` multiplatform is in progress but in the meantime can we switch to https://github.com/Kamel-Media/Kamel for network image loading? It will make this library at least usable on the non-android targets. 

I can contribute to this if we decide to proceed.

**Comment by mikepenz** [comment]
Good day @psuzn thank you for the proposal. 

I'd actually say that the best solution will be to not enforce any specific image loading solution, and instead make it configurable, so it is possible for the integrating engineer to pick different solutions. 

Long term I would love to provide `coil` as default, but I believe allowing the flexibility there is going to be a huge benefit

**Comment by psuzn** [comment]
I completely agree with you. I'm hoping to use it on one of the projects and just want it to be functional for now.
