### ISSUE TITLE
bug: no links in header

### ISSUE THREAD

**Issue by Ushie** [mikepenz/multiplatform-markdown-renderer#78]
## About this issue

- Briefly describe the issue:

Links can't be used in Headers
<details>
<summary>Image:</summary>
<br>

![image](https://github.com/mikepenz/multiplatform-markdown-renderer/assets/79272171/eb434259-1d73-4ec8-955a-bc0d1ccc6b63)

</details>

- How can the issue be reproduced / sample code
```kt
    val markdown = """
    # [This doesnt work](https://github.com/)
    [This works](https://github.com/)""".trimIndent()

    Markdown(
        content = markdown,
        colors = markdownColor(
            text = MaterialTheme.colorScheme.onSurfaceVariant,
            codeBackground = MaterialTheme.colorScheme.secondaryContainer,
            codeText = MaterialTheme.colorScheme.onSecondaryContainer
        ),
        typography = markdownTypography(
            h1 = MaterialTheme.typography.headlineSmall.copy(fontWeight = FontWeight.Bold),
            h2 = MaterialTheme.typography.titleLarge.copy(fontWeight = FontWeight.Bold),
            h3 = MaterialTheme.typography.titleMedium.copy(fontWeight = FontWeight.Bold),
            text = MaterialTheme.typography.bodyMedium,
            list = MaterialTheme.typography.bodyMedium
        )
    )
```

## Details
- v0.8.0
- Android

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/multiplatform-markdown-renderer/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/multiplatform-markdown-renderer/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/multiplatform-markdown-renderer/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
Thank you very much for the report. Will look into this as soon as I have time
