### ISSUE TITLE
bug: v0.9.0 does not support iOS 

### ISSUE THREAD

**Issue by Ovaltinezz** [mikepenz/multiplatform-markdown-renderer#87]
## About this issue

- Briefly describe the issue
I'm working on a KMM project. I can't run the iosApp if I use v0.9.0 of markdown-renderer, while v0.7.2 works fine. It seems because the iOS target was deleted accidentally when [upgraded to compose 1.5.4](https://github.com/mikepenz/multiplatform-markdown-renderer/commit/3f02042c32a3094fc2983000b018f4892707916a)
```
> Could not resolve com.mikepenz:multiplatform-markdown-renderer:0.9.0.
     Required by:
         project :shared
      > No matching variant of com.mikepenz:multiplatform-markdown-renderer:0.9.0 was found. The consumer was configured to find a library for use during 'kotlin-metadata', preferably optimized for non-jvm, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native', attribute 'org.jetbrains.kotlin.native.target' with value 'ios_x64' but:
          - Variant 'iosSimulatorArm64ApiElements-published' capability com.mikepenz:multiplatform-markdown-renderer:0.9.0 declares a library for use during 'kotlin-api', as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'ios_simulator_arm64' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'ios_x64'
              - Other compatible attribute:
                  - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
```

## Details
- [ `0.9.0` ] Used library version

**Comment by mikepenz** [comment]
The iOS target should come from the default hiararchy 🤔 :
https://github.com/mikepenz/multiplatform-markdown-renderer/commit/3f02042c32a3094fc2983000b018f4892707916a#diff-4d1366c1d930d53bf81d4ba1b86de7928596f427413946f76ddae7db25ca4de4R56

That said. you are right, they miss from maven central 
https://repo1.maven.org/maven2/com/mikepenz/multiplatform-markdown-renderer-iosx64/
https://repo1.maven.org/maven2/com/mikepenz/multiplatform-markdown-renderer-iosarm64/

Will look into it
